import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Eye, Pencil, Plus, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { formatTwd, HRLayout } from "./HRLayout";

export default function HRAdvances() {
  const employees = trpc.payroll.employees.list.useQuery(); const periods = trpc.payroll.periods.list.useQuery(); const rows = trpc.payroll.advances.list.useQuery(); const utils = trpc.useUtils();
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<number | null>(null); const [editing, setEditing] = useState<any>(null); const detail = trpc.payroll.advances.detail.useQuery({ id: selected || 0 }, { enabled: !!selected });
  const refresh = () => { void utils.payroll.advances.list.invalidate(); void utils.payroll.runs.invalidate(); };
  const create = trpc.payroll.advances.create.useMutation({ onSuccess: () => { toast.success("借支已建立"); setOpen(false); refresh(); }, onError: e => toast.error(e.message) });
  const update = trpc.payroll.advances.update.useMutation({ onSuccess: () => { toast.success("借支資料已更新，已保留修改紀錄"); setEditing(null); refresh(); }, onError: e => toast.error(e.message) });
  const repay = trpc.payroll.advances.repay.useMutation({ onSuccess: result => { toast.success(result.deductionId ? "扣回已代入本期扣款並重新試算薪資" : "扣回已記錄，尚未指定薪資週期"); setSelected(null); refresh(); }, onError: e => toast.error(e.message) });
  const submitCreate = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); create.mutate({ employeeId: Number(f.get("employeeId")), advanceDate: String(f.get("advanceDate")), originalAmount: String(f.get("amount")), notes: String(f.get("notes")) || null }); };
  const submitEdit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); update.mutate({ id: editing.id, advanceDate: String(f.get("advanceDate")), originalAmount: String(f.get("amount")), notes: String(f.get("notes")) || null }); };
  const submitRepay = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); repay.mutate({ advanceId: selected!, payrollPeriodId: String(f.get("periodId")) ? Number(f.get("periodId")) : null, repaymentDate: String(f.get("repaymentDate")), amount: String(f.get("amount")), notes: String(f.get("notes")) || null }); };
  return <HRLayout title="借支管理" description="檢視每筆借支與扣回歷程；選擇草稿薪資週期扣回時，系統會自動帶入本期扣款並重新試算實發薪資。">
    <div className="flex justify-end"><Button className="bg-[#163C72]" onClick={() => setOpen(!open)}><Plus className="mr-2 h-4 w-4" />新增借支</Button></div>
    {open && <Card className="mt-5 p-5"><form className="grid gap-4 md:grid-cols-4" onSubmit={submitCreate}><div><Label>員工</Label><select name="employeeId" className="mt-2 h-10 w-full rounded-md border px-3 text-sm" required><option value="">選擇員工</option>{employees.data?.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select></div><div><Label>借支日期</Label><Input type="date" name="advanceDate" required /></div><div><Label>借支金額</Label><Input type="number" name="amount" min="1" required /></div><div><Label>備註</Label><Input name="notes" /></div><div className="md:col-span-4"><Button disabled={create.isPending}>儲存借支</Button></div></form></Card>}
    {editing && <Card role="dialog" aria-label="編輯借支" className="mt-5 border-[#8CC63F] p-5"><div className="mb-3 flex justify-between"><div><h2 className="font-semibold text-[#163C72]">編輯借支資料</h2><p className="text-sm text-slate-600">原始金額不能低於歷史已扣回金額。</p></div><Button size="icon" variant="ghost" onClick={() => setEditing(null)}><X className="h-4 w-4" /></Button></div><form className="grid gap-4 md:grid-cols-3" onSubmit={submitEdit}><div><Label>借支日期</Label><Input type="date" name="advanceDate" defaultValue={editing.advanceDate} required /></div><div><Label>原始金額</Label><Input type="number" name="amount" min="1" defaultValue={editing.originalAmount} required /></div><div><Label>備註</Label><Input name="notes" defaultValue={editing.notes || ""} /></div><div className="md:col-span-3"><Button disabled={update.isPending}>儲存變更</Button></div></form></Card>}
    {selected && <Card role="dialog" aria-label="借支明細" className="mt-5 border-blue-100 p-5"><div className="flex justify-between"><div><h2 className="font-semibold text-[#163C72]">借支明細與扣回</h2><p className="text-sm text-slate-600">選擇薪資週期後，扣回金額將立即成為該期扣款。</p></div><Button size="icon" variant="ghost" onClick={() => setSelected(null)}><X className="h-4 w-4" /></Button></div><div className="my-4 rounded-md bg-slate-50 p-3 text-sm">{detail.data?.repayments.length ? detail.data.repayments.map(item => <p key={item.id}>{item.repaymentDate}：{formatTwd(item.amount)}{item.payrollPeriodId ? `（薪資週期 #${item.payrollPeriodId}）` : "（僅記錄）"}</p>) : "尚無扣回紀錄"}</div><form className="grid gap-3 md:grid-cols-4" onSubmit={submitRepay}><div><Label>薪資週期</Label><select name="periodId" className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">不代入薪資</option>{periods.data?.map(i => <option key={i.id} value={i.id}>{i.label}（{i.status}）</option>)}</select></div><div><Label>扣回日期</Label><Input type="date" name="repaymentDate" required /></div><div><Label>本期扣款金額</Label><Input type="number" name="amount" min="1" required /></div><div><Label>備註</Label><Input name="notes" /></div><div className="md:col-span-4"><Button disabled={repay.isPending}>確認扣回並同步薪資</Button></div></form></Card>}
    <Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">員工／借支日</th><th className="px-5 py-3">原始金額</th><th className="px-5 py-3">已扣回／尚欠</th><th className="px-5 py-3 text-right">操作</th></tr></thead><tbody>{rows.data?.map(row => <tr key={row.id} className="border-t"><td className="px-5 py-3">{employees.data?.find(i => i.id === row.employeeId)?.name || `#${row.employeeId}`}<p className="text-xs text-slate-500">{row.advanceDate}</p></td><td className="px-5 py-3">{formatTwd(row.originalAmount)}</td><td className="px-5 py-3">{formatTwd(row.repaidAmount)}／<b>{formatTwd(row.outstandingAmount)}</b></td><td className="px-5 py-3 text-right"><Button size="sm" variant="outline" onClick={() => setSelected(row.id)}><Eye className="mr-1 h-3 w-3" />檢視／扣回</Button><Button size="sm" variant="outline" className="ml-2" onClick={() => setEditing(row)}><Pencil className="mr-1 h-3 w-3" />編輯</Button></td></tr>)}{!rows.data?.length && <tr><td colSpan={4} className="px-5 py-10 text-center text-slate-500">尚無借支資料。</td></tr>}</tbody></table></div></Card>
  </HRLayout>;
}
