import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { formatTwd, HRLayout } from "./HRLayout";

export default function HRAdvances() { const employees = trpc.payroll.employees.list.useQuery(); const rows = trpc.payroll.advances.list.useQuery(); const utils = trpc.useUtils(); const create = trpc.payroll.advances.create.useMutation({ onSuccess: () => { toast.success("借支已建立"); void utils.payroll.advances.list.invalidate(); } }); const repay = trpc.payroll.advances.repay.useMutation({ onSuccess: () => { toast.success("借支扣回已紀錄"); void utils.payroll.advances.list.invalidate(); } }); const [open, setOpen] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); create.mutate({ employeeId: Number(f.get("employeeId")), advanceDate: String(f.get("advanceDate")), originalAmount: String(f.get("amount")), notes: String(f.get("notes") || "") || null }); };
 return <HRLayout title="借支管理" description="依每筆借支保存原始金額、歷史扣回與尚欠餘額，未清餘額會持續跨期帶入。"><div className="flex justify-end"><Button className="bg-[#163C72]" onClick={() => setOpen(!open)}><Plus className="mr-2 h-4 w-4"/>新增借支</Button></div>{open && <Card className="mt-5 p-5"><form className="grid gap-4 md:grid-cols-4" onSubmit={submit}><div><Label>員工</Label><select name="employeeId" className="mt-2 h-10 w-full rounded-md border px-3 text-sm" required><option value="">選擇員工</option>{employees.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label>借支日期</Label><Input type="date" name="advanceDate" required/></div><div><Label>借支金額</Label><Input type="number" name="amount" min="1" required/></div><div className="flex items-end"><Button disabled={create.isPending}>儲存</Button></div></form></Card>}<Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">員工</th><th className="px-5 py-3">借支日</th><th className="px-5 py-3">原始金額</th><th className="px-5 py-3">已扣回</th><th className="px-5 py-3">尚欠</th><th className="px-5 py-3">操作</th></tr></thead><tbody>{rows.data?.map((row) => <tr key={row.id} className="border-t"><td className="px-5 py-3">{employees.data?.find((item) => item.id === row.employeeId)?.name || `#${row.employeeId}`}</td><td className="px-5 py-3">{row.advanceDate}</td><td className="px-5 py-3">{formatTwd(row.originalAmount)}</td><td className="px-5 py-3">{formatTwd(row.repaidAmount)}</td><td className="px-5 py-3 font-semibold">{formatTwd(row.outstandingAmount)}</td><td className="px-5 py-3">{Number(row.outstandingAmount) > 0 ? <Button size="sm" variant="outline" onClick={() => { const amount = window.prompt("本次扣回金額（元）"); if (amount) repay.mutate({ advanceId: row.id, repaymentDate: new Date().toISOString().slice(0, 10), amount }); }}>扣回</Button> : "已結清"}</td></tr>)}{!rows.data?.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-slate-500">尚無借支資料。</td></tr>}</tbody></table></div></Card></HRLayout>; }
