import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { HRLayout, monthRange } from "./HRLayout";

export default function HRAttendance() { const range = monthRange(); const employees = trpc.payroll.employees.list.useQuery(); const records = trpc.payroll.attendance.list.useQuery({ startDate: range.start, endDate: range.end }); const utils = trpc.useUtils(); const create = trpc.payroll.attendance.create.useMutation({ onSuccess: () => { toast.success("出勤紀錄已儲存"); void utils.payroll.attendance.list.invalidate(); } }); const [open, setOpen] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); create.mutate({ employeeId: Number(f.get("employeeId")), workDate: String(f.get("workDate")), workHours: String(f.get("workHours")), status: String(f.get("status")) as "present", actualStartTime: String(f.get("actualStartTime") || "") || null, actualEndTime: String(f.get("actualEndTime") || "") || null, lateMinutes: Number(f.get("lateMinutes") || 0), earlyLeaveMinutes: Number(f.get("earlyLeaveMinutes") || 0) }); };
return <HRLayout title="出勤管理" description="記錄實際出退勤、工時、遲到、早退、請假與餐費計算所需資料。"><div className="flex justify-between"><p className="text-sm text-slate-500">本月出勤</p><Button onClick={() => setOpen(!open)} className="bg-[#163C72]"><Plus className="mr-2 h-4 w-4"/>新增出勤</Button></div>{open && <Card className="mt-5 p-5"><form onSubmit={submit} className="grid gap-4 md:grid-cols-4"><div><Label>員工</Label><select name="employeeId" required className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">選擇員工</option>{employees.data?.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></div><div><Label>日期</Label><Input name="workDate" type="date" required/></div><div><Label>工時</Label><Input name="workHours" type="number" step="0.25" required/></div><div><Label>狀態</Label><select name="status" className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="present">正常出勤</option><option value="half_day">半日</option><option value="late">遲到</option><option value="early_leave">早退</option><option value="leave">請假</option><option value="absent">未到</option></select></div><div><Label>實際上班</Label><Input name="actualStartTime" type="time"/></div><div><Label>實際下班</Label><Input name="actualEndTime" type="time"/></div><div><Label>遲到分鐘</Label><Input name="lateMinutes" type="number" defaultValue="0"/></div><div><Label>早退分鐘</Label><Input name="earlyLeaveMinutes" type="number" defaultValue="0"/></div><Button disabled={create.isPending}>儲存出勤</Button></form></Card>}<Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">日期</th><th className="px-5 py-3">員工</th><th className="px-5 py-3">工時</th><th className="px-5 py-3">狀態</th><th className="px-5 py-3">遲到／早退</th></tr></thead><tbody>{records.data?.map((row) => <tr key={row.id} className="border-t"><td className="px-5 py-3">{row.workDate}</td><td className="px-5 py-3">{employees.data?.find((employee) => employee.id === row.employeeId)?.name || `#${row.employeeId}`}</td><td className="px-5 py-3">{row.workHours} 小時</td><td className="px-5 py-3">{row.status}</td><td className="px-5 py-3">{row.lateMinutes}／{row.earlyLeaveMinutes} 分鐘</td></tr>)}{!records.data?.length && <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">本期間尚無出勤資料。</td></tr>}</tbody></table></div></Card></HRLayout>; }
