import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Eye, Gift, MinusCircle, Pencil } from "lucide-react";
import { FormEvent } from "react";
import { toast } from "sonner";
import { formatTwd, HRLayout } from "./HRLayout";

export default function HRCompensation() {
 const employees=trpc.payroll.employees.list.useQuery(), periods=trpc.payroll.periods.list.useQuery(), bonuses=trpc.payroll.bonuses.list.useQuery(), deductions=trpc.payroll.deductions.list.useQuery(), utils=trpc.useUtils();
 const refresh=()=>{void utils.payroll.bonuses.list.invalidate();void utils.payroll.deductions.list.invalidate();void utils.payroll.runs.invalidate();};
 const bonus=trpc.payroll.bonuses.create.useMutation({onSuccess:()=>{toast.success("獎金／津貼已新增，重新試算薪資後會帶入本期");refresh();},onError:e=>toast.error(e.message)}), deduction=trpc.payroll.deductions.create.useMutation({onSuccess:()=>{toast.success("扣款已新增，重新試算薪資後會帶入本期");refresh();},onError:e=>toast.error(e.message)});
 const updateBonus=trpc.payroll.bonuses.update.useMutation({onSuccess:()=>{toast.success("獎金／津貼已更新，已保留稽核紀錄");refresh();},onError:e=>toast.error(e.message)}), updateDeduction=trpc.payroll.deductions.update.useMutation({onSuccess:()=>{toast.success("扣款已更新，已保留稽核紀錄");refresh();},onError:e=>toast.error(e.message)});
 const submitBonus=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);bonus.mutate({employeeId:Number(f.get("employeeId")),payrollPeriodId:Number(f.get("periodId")),bonusDate:String(f.get("date")),name:String(f.get("name")),amount:String(f.get("amount")),notes:String(f.get("notes"))||null});};
 const submitDeduction=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);deduction.mutate({employeeId:Number(f.get("employeeId")),payrollPeriodId:Number(f.get("periodId")),deductionDate:String(f.get("date")),type:String(f.get("type")) as any,amount:String(f.get("amount")),notes:String(f.get("notes"))||null});};
 const editBonus=(r:any)=>{const name=window.prompt("名稱",r.name),amount=window.prompt("金額",r.amount);if(name&&amount)updateBonus.mutate({...r,name,amount});}; const editDeduction=(r:any)=>{const amount=window.prompt("金額",r.amount),notes=window.prompt("說明",r.notes||"");if(amount)updateDeduction.mutate({...r,amount,notes:notes||null});};
 const selectors=<><div><Label>員工</Label><select name="employeeId" required className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">選擇員工</option>{employees.data?.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></div><div><Label>薪資週期</Label><select name="periodId" required className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">選擇週期</option>{periods.data?.map(i=><option key={i.id} value={i.id}>{i.label}（{i.status}）</option>)}</select></div></>;
 return <HRLayout title="獎金／津貼管理" description="可檢視與編輯收入、扣款明細。已確認或已發薪的週期會自動禁止變更。"><div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><div className="flex gap-2"><Gift className="h-5 w-5 text-[#8CC63F]"/><h3 className="font-bold">新增獎金／津貼</h3></div><form className="mt-5 grid gap-3 md:grid-cols-2" onSubmit={submitBonus}>{selectors}<div><Label>日期</Label><Input name="date" type="date" required/></div><div><Label>名稱</Label><Input name="name" required/></div><div><Label>金額</Label><Input name="amount" type="number" min="0" required/></div><div><Label>備註</Label><Input name="notes"/></div><Button disabled={bonus.isPending}>新增收入</Button></form></Card><Card className="p-5"><div className="flex gap-2"><MinusCircle className="h-5 w-5 text-rose-500"/><h3 className="font-bold">新增扣款</h3></div><form className="mt-5 grid gap-3 md:grid-cols-2" onSubmit={submitDeduction}>{selectors}<div><Label>日期</Label><Input name="date" type="date" required/></div><div><Label>類型</Label><select name="type" className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="labor_insurance">勞保自付</option><option value="health_insurance">健保自付</option><option value="late">遲到</option><option value="early_leave">早退</option><option value="absence">缺勤</option><option value="other">其他</option></select></div><div><Label>金額</Label><Input name="amount" type="number" min="0" required/></div><div><Label>說明</Label><Input name="notes"/></div><Button variant="outline" disabled={deduction.isPending}>新增扣款</Button></form></Card></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="overflow-hidden"><h3 className="p-5 font-bold">獎金／津貼明細</h3><table className="w-full text-sm"><tbody>{bonuses.data?.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.name}<p className="text-xs text-slate-500">{r.bonusDate}・週期 #{r.payrollPeriodId}</p></td><td>{formatTwd(r.amount)}</td><td className="text-right"><Button size="sm" variant="outline" title="檢視與編輯" onClick={()=>editBonus(r)}><Eye className="mr-1 h-3 w-3"/><Pencil className="h-3 w-3"/></Button></td></tr>)}{!bonuses.data?.length&&<tr><td className="p-5 text-slate-500">尚無獎金／津貼。</td></tr>}</tbody></table></Card><Card className="overflow-hidden"><h3 className="p-5 font-bold">扣款明細</h3><table className="w-full text-sm"><tbody>{deductions.data?.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.type}<p className="text-xs text-slate-500">{r.deductionDate}・週期 #{r.payrollPeriodId}</p></td><td>{formatTwd(r.amount)}</td><td className="text-right">{r.advanceRepaymentId?"借支扣回":<Button size="sm" variant="outline" title="檢視與編輯" onClick={()=>editDeduction(r)}><Eye className="mr-1 h-3 w-3"/><Pencil className="h-3 w-3"/></Button>}</td></tr>)}{!deductions.data?.length&&<tr><td className="p-5 text-slate-500">尚無扣款。</td></tr>}</tbody></table></Card></div></HRLayout>;
}
