import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Gift, MinusCircle } from "lucide-react";
import { FormEvent } from "react";
import { toast } from "sonner";
import { HRLayout } from "./HRLayout";

export default function HRCompensation() { const employees = trpc.payroll.employees.list.useQuery(); const periods = trpc.payroll.periods.list.useQuery(); const utils = trpc.useUtils(); const bonus = trpc.payroll.bonuses.create.useMutation({ onSuccess: () => { toast.success("獎金／津貼已新增"); void utils.payroll.runs.list.invalidate(); } }); const deduction = trpc.payroll.deductions.create.useMutation({ onSuccess: () => { toast.success("扣款已新增"); void utils.payroll.runs.list.invalidate(); } }); const submitBonus = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); bonus.mutate({ employeeId: Number(f.get("employeeId")), payrollPeriodId: Number(f.get("periodId")), bonusDate: String(f.get("date")), name: String(f.get("name")), amount: String(f.get("amount")) }); }; const submitDeduction = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); deduction.mutate({ employeeId: Number(f.get("employeeId")), payrollPeriodId: Number(f.get("periodId")), deductionDate: String(f.get("date")), type: String(f.get("type")) as "other", amount: String(f.get("amount")), notes: String(f.get("name")) }); }; const selectors = <><div><Label>員工</Label><select name="employeeId" required className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">選擇員工</option>{employees.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label>薪資週期</Label><select name="periodId" required className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">選擇週期</option>{periods.data?.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div></>;
return <HRLayout title="獎金／津貼管理" description="將獎金、全勤、交通或其他收入與勞健保、遲早到等扣款以可追溯明細納入指定薪資週期。"><div className="grid gap-6 xl:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-2"><Gift className="h-5 w-5 text-[#8CC63F]"/><h3 className="font-bold">新增獎金／津貼</h3></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={submitBonus}>{selectors}<div><Label>日期</Label><Input name="date" type="date" required/></div><div><Label>名稱</Label><Input name="name" placeholder="全勤獎金、交通補助" required/></div><div><Label>金額</Label><Input name="amount" type="number" min="0" required/></div><div className="flex items-end"><Button disabled={bonus.isPending}>新增收入</Button></div></form></Card><Card className="p-5"><div className="flex items-center gap-2"><MinusCircle className="h-5 w-5 text-rose-500"/><h3 className="font-bold">新增扣款</h3></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={submitDeduction}>{selectors}<div><Label>日期</Label><Input name="date" type="date" required/></div><div><Label>扣款類型</Label><select name="type" className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="labor_insurance">勞保自付</option><option value="health_insurance">健保自付</option><option value="late">遲到扣款</option><option value="early_leave">早退扣款</option><option value="absence">缺勤扣款</option><option value="other">其他扣款</option></select></div><div><Label>說明</Label><Input name="name" placeholder="扣款原因"/></div><div><Label>金額</Label><Input name="amount" type="number" min="0" required/></div><div className="flex items-end"><Button variant="outline" disabled={deduction.isPending}>新增扣款</Button></div></form></Card></div></HRLayout>; }
