import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Banknote, BarChart3, Clock3, UsersRound, WalletCards } from "lucide-react";
import React, { useMemo, useState } from "react";
import { formatTwd, HRLayout } from "./HRLayout";

export default function HRDashboard() {
  const periods = trpc.payroll.periods.list.useQuery();
  const [periodId, setPeriodId] = useState<number | null>(null);
  const activePeriodId = periodId ?? periods.data?.[0]?.id ?? null;
  const summary = trpc.payroll.dashboard.summary.useQuery(activePeriodId ? { payrollPeriodId: activePeriodId } : undefined);
  const data = summary.data;
  const cards = [["在職員工", data?.employeeCount ?? 0, UsersRound, "text-[#163C72]"], ["本期薪資條", data?.payrollRunCount ?? 0, WalletCards, "text-[#163C72]"], ["待發薪", data?.pendingPayments ?? 0, Clock3, "text-amber-600"], ["本期實發", formatTwd(data?.netPay), Banknote, "text-[#8CC63F]"]] as const;
  const maxTrend = useMemo(() => Math.max(...(data?.payrollTrend?.map((item) => Number(item.netPay)) ?? [0]), 1), [data?.payrollTrend]);
  return <HRLayout title="首頁 Dashboard" description="掌握選定週期的人力、薪資、待辦與最近十二期薪資支出趨勢。"><div className="mb-5 flex justify-end"><select value={activePeriodId ?? ""} onChange={(event) => setPeriodId(Number(event.target.value))} className="h-10 min-w-56 rounded-md border bg-white px-3 text-sm">{periods.data?.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <Card key={label} className="border-slate-200 p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p></div><Icon className={`h-7 w-7 ${color}`} /></div></Card>)}</div><section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card className="border-slate-200 p-6 shadow-sm"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-[#163C72]"/><h3 className="font-bold">近十二期薪資支出趨勢</h3></div><p className="mt-1 text-sm text-slate-500">{data?.selectedPeriod ? `${data.selectedPeriod.label}｜${data.selectedPeriod.periodStart} 至 ${data.selectedPeriod.periodEnd}` : "尚未建立薪資週期"}</p><div className="mt-6 flex h-56 items-end gap-2 rounded-2xl bg-gradient-to-br from-slate-50 to-blue-50 p-4">{data?.payrollTrend?.length ? data.payrollTrend.map((item) => <div key={item.id} className="flex min-w-0 flex-1 flex-col justify-end gap-2"><div className="group relative rounded-t-md bg-[#163C72] transition hover:bg-[#8CC63F]" style={{ height: `${Math.max(6, (Number(item.netPay) / maxTrend) * 100)}%` }} title={`${item.label}：${formatTwd(item.netPay)}`}><span className="pointer-events-none absolute -top-7 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded bg-slate-900 px-2 py-1 text-xs text-white group-hover:block">{formatTwd(item.netPay)}</span></div><p className="truncate text-center text-[10px] text-slate-500">{item.label.replace(/\d{4} 年 /, "")}</p></div>) : <p className="m-auto text-sm text-slate-500">尚無已試算薪資資料可供趨勢分析。</p>}</div></Card><Card className="border-slate-200 p-6 shadow-sm"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-500"/><h3 className="font-bold">異常與待辦</h3></div><div className="mt-4 space-y-3">{data?.unresolvedAlerts?.length ? data.unresolvedAlerts.slice(0, 5).map((alert) => <div key={alert.id} className="rounded-xl bg-amber-50 px-4 py-3"><p className="font-medium capitalize text-amber-900">{alert.type.replace(/_/g, " ")}</p><p className="mt-1 text-xs text-amber-700">{alert.message}</p></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">目前沒有未處理的薪資異常。</p>}</div></Card></section></HRLayout>;
}
