import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Loader2, Plus, Search } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { HRLayout } from "./HRLayout";

export default function HREmployees() {
  const access = trpc.payroll.access.useQuery();
  const employees = trpc.payroll.employees.list.useQuery(undefined, { enabled: access.data?.canManageOperations });
  const utils = trpc.useUtils();
  const create = trpc.payroll.employees.create.useMutation({ onSuccess: () => { toast.success("員工資料已建立"); void utils.payroll.employees.list.invalidate(); } });
  const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false);
  const rows = useMemo(() => (employees.data ?? []).filter((item) => `${item.name}${item.employeeCode ?? ""}${item.phone ?? ""}`.toLowerCase().includes(query.toLowerCase())), [employees.data, query]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: String(form.get("name")), employeeCode: String(form.get("employeeCode") || "") || null, phone: String(form.get("phone") || "") || null, jobTitle: String(form.get("jobTitle") || "") || null, hireDate: String(form.get("hireDate")), bankName: String(form.get("bankName") || "") || null, bankAccount: String(form.get("bankAccount") || "") || null }); };
  return <HRLayout title="員工管理" description="管理員工主檔、在離職狀態、銀行資料與獨立薪資設定。"><div className="flex flex-wrap items-center justify-between gap-3"><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="搜尋姓名、員工編號或電話"/></div>{access.data?.canManagePayroll && <Button className="bg-[#163C72] hover:bg-[#102e59]" onClick={() => setShowForm(!showForm)}><Plus className="mr-2 h-4 w-4"/>新增員工</Button>}</div>{showForm && <Card className="mt-5 border-slate-200 p-5"><form className="grid gap-4 md:grid-cols-3" onSubmit={submit}><div><Label>姓名 *</Label><Input name="name" required /></div><div><Label>員工編號</Label><Input name="employeeCode"/></div><div><Label>到職日期 *</Label><Input name="hireDate" type="date" required/></div><div><Label>電話</Label><Input name="phone"/></div><div><Label>職稱</Label><Input name="jobTitle"/></div><div><Label>銀行名稱</Label><Input name="bankName"/></div><div className="md:col-span-2"><Label>銀行帳號（加密儲存）</Label><Input name="bankAccount" inputMode="numeric"/></div><div className="flex items-end gap-2"><Button disabled={create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin"/>}建立員工</Button><Button type="button" variant="outline" onClick={() => setShowForm(false)}>取消</Button></div></form></Card>}<Card className="mt-5 overflow-hidden border-slate-200 shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">員工</th><th className="px-5 py-3">職稱</th><th className="px-5 py-3">電話</th><th className="px-5 py-3">銀行</th><th className="px-5 py-3">狀態</th></tr></thead><tbody>{employees.isLoading ? <tr><td colSpan={5} className="px-5 py-10 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin"/></td></tr> : rows.map((employee) => <tr key={employee.id} className="border-t border-slate-100"><td className="px-5 py-4"><p className="font-semibold">{employee.name}</p><p className="text-xs text-slate-500">{employee.employeeCode || "未設定編號"}</p></td><td className="px-5 py-4">{employee.jobTitle || "—"}</td><td className="px-5 py-4">{employee.phone || "—"}</td><td className="px-5 py-4">{employee.bankName ? `${employee.bankName} ${employee.bankAccountMasked || ""}` : "未設定"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${employee.employmentStatus === "active" ? "bg-lime-100 text-lime-800" : "bg-slate-100 text-slate-600"}`}>{employee.employmentStatus === "active" ? "在職" : employee.employmentStatus}</span></td></tr>)}{!employees.isLoading && rows.length === 0 && <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">尚無符合條件的員工資料。</td></tr>}</tbody></table></div></Card></HRLayout>;
}
