import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Plus, XCircle } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { formatTwd, HRLayout, monthRange } from "./HRLayout";

export default function HROvertime() { const range = monthRange(); const access = trpc.payroll.access.useQuery(); const employees = trpc.payroll.employees.list.useQuery(); const rows = trpc.payroll.overtime.list.useQuery({ startDate: range.start, endDate: range.end }); const utils = trpc.useUtils(); const create = trpc.payroll.overtime.create.useMutation({ onSuccess: () => { toast.success("加班申請已建立"); void utils.payroll.overtime.list.invalidate(); } }); const review = trpc.payroll.overtime.review.useMutation({ onSuccess: () => { toast.success("加班審核已更新"); void utils.payroll.overtime.list.invalidate(); } }); const [open, setOpen] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const hours = String(f.get("hours")); const rate = Number(f.get("hourlyRate") || 0); create.mutate({ employeeId: Number(f.get("employeeId")), workDate: String(f.get("workDate")), startTime: String(f.get("startTime")), endTime: String(f.get("endTime")), hours, calculatedAmount: (Number(hours) * rate).toFixed(2), manualAmount: String(f.get("manualAmount") || "") || null, notes: String(f.get("notes") || "") || null }); };
return <HRLayout title="加班管理" description="獨立記錄加班時數與費用；可依員工設定計算或由授權人員人工調整。"><div className="flex justify-between"><p className="text-sm text-slate-500">本月加班申請與審核</p><Button className="bg-[#163C72]" onClick={() => setOpen(!open)}><Plus className="mr-2 h-4 w-4"/>新增加班</Button></div>{open && <Card className="mt-5 p-5"><form className="grid gap-4 md:grid-cols-4" onSubmit={submit}><div><Label>員工</Label><select name="employeeId" required className="mt-2 h-10 w-full rounded-md border px-3 text-sm"><option value="">選擇員工</option>{employees.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label>日期</Label><Input name="workDate" type="date" required/></div><div><Label>開始／結束</Label><div className="flex gap-2"><Input name="startTime" type="time" required/><Input name="endTime" type="time" required/></div></div><div><Label>時數</Label><Input name="hours" type="number" step="0.25" required/></div><div><Label>每小時費率（試算）</Label><Input name="hourlyRate" type="number" step="0.01" required/></div><div><Label>人工金額覆寫</Label><Input name="manualAmount" type="number" step="1"/></div><div className="flex items-end"><Button disabled={create.isPending}>儲存加班</Button></div></form></Card>}<Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">日期／員工</th><th className="px-5 py-3">時數</th><th className="px-5 py-3">加班費</th><th className="px-5 py-3">狀態</th><th className="px-5 py-3">操作</th></tr></thead><tbody>{rows.data?.map((row) => <tr className="border-t" key={row.id}><td className="px-5 py-3"><p>{row.workDate}</p><p className="text-xs text-slate-500">{employees.data?.find((item) => item.id === row.employeeId)?.name || `#${row.employeeId}`}</p></td><td className="px-5 py-3">{row.hours} 小時</td><td className="px-5 py-3">{formatTwd(row.manualAmount || row.calculatedAmount)}</td><td className="px-5 py-3">{row.status}</td><td className="px-5 py-3">{row.status === "pending" && access.data?.canManageOperations ? <div className="flex gap-2"><Button size="sm" onClick={() => review.mutate({ id: row.id, status: "approved" })}><CheckCircle2 className="mr-1 h-3 w-3"/>核准</Button><Button size="sm" variant="outline" onClick={() => review.mutate({ id: row.id, status: "rejected" })}><XCircle className="mr-1 h-3 w-3"/>退回</Button></div> : "—"}</td></tr>)}{!rows.data?.length && <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">本期間尚無加班資料。</td></tr>}</tbody></table></div></Card></HRLayout>; }
