import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { HRLayout, monthRange } from "./HRLayout";

export default function HRSchedule() { const range = monthRange(); const employees = trpc.payroll.employees.list.useQuery(); const schedules = trpc.payroll.schedules.list.useQuery({ startDate: range.start, endDate: range.end }); const utils = trpc.useUtils(); const create = trpc.payroll.schedules.create.useMutation({ onSuccess: () => { toast.success("排班已建立"); void utils.payroll.schedules.list.invalidate(); } }); const [open, setOpen] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); create.mutate({ employeeId: Number(f.get("employeeId")), workDate: String(f.get("workDate")), startTime: String(f.get("startTime")), endTime: String(f.get("endTime")), location: String(f.get("location") || "") || null, notes: String(f.get("notes") || "") || null }); };
return <HRLayout title="排班管理" description="以月曆期間集中檢視；同一位員工可在同一天建立多個工作時段。"><div className="flex justify-between"><p className="text-sm text-slate-500">本月：{range.start} 至 {range.end}</p><Button onClick={() => setOpen(!open)} className="bg-[#163C72]"><Plus className="mr-2 h-4 w-4"/>新增排班</Button></div>{open && <Card className="mt-5 p-5"><form onSubmit={submit} className="grid gap-4 md:grid-cols-3"><div><Label>員工</Label><select name="employeeId" required className="mt-2 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">選擇員工</option>{employees.data?.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></div><div><Label>日期</Label><Input name="workDate" type="date" required/></div><div><Label>工作地點</Label><Input name="location"/></div><div><Label>開始時間</Label><Input name="startTime" type="time" required/></div><div><Label>結束時間</Label><Input name="endTime" type="time" required/></div><div className="flex items-end"><Button disabled={create.isPending}>儲存排班</Button></div></form></Card>}<Card className="mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-5 py-3">日期</th><th className="px-5 py-3">時段</th><th className="px-5 py-3">員工</th><th className="px-5 py-3">地點</th><th className="px-5 py-3">狀態</th></tr></thead><tbody>{schedules.data?.map((row) => <tr key={row.id} className="border-t"><td className="px-5 py-3">{row.workDate}</td><td className="px-5 py-3">{row.startTime}–{row.endTime}</td><td className="px-5 py-3">{employees.data?.find((employee) => employee.id === row.employeeId)?.name || `#${row.employeeId}`}</td><td className="px-5 py-3">{row.location || "—"}</td><td className="px-5 py-3">{row.status}</td></tr>)}{!schedules.data?.length && <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">本期間尚無排班資料。</td></tr>}</tbody></table></div></Card></HRLayout>; }
